version: 0.2
phases:
  install:
    commands:
      - export LANG=en_US.UTF-8

  pre_build:
    commands:
      # Python environment setup
      - pip install pipenv
      - pipenv install
      - pipenv run pip freeze

      # ECR login
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 490602924632.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      # Run unit tests with enhanced output
      - echo Running unit tests...
      - pipenv run python -m pytest -v --show-capture=all -s --durations=3

      # Build Docker image
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t python-flask .
      - docker tag python-flask:latest 490602924632.dkr.ecr.us-east-1.amazonaws.com/python-flask:latest

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 490602924632.dkr.ecr.us-east-1.amazonaws.com/python-flask:latest

artifacts:
  files:
    - "**/*"
