version: 0.2
phases:
  install:
    commands:
      - export LANG=en_US.UTF-8

  pre_build:
    commands:
      # Python environment setup
      - pip install pipenv
      - pipenv install
      - pipenv run pip freeze

      # ECR login
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 490602924632.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      # Run unit tests with enhanced output
      - echo Running unit tests...
      - pipenv run python -m pytest -v --show-capture=all -s --durations=3

      # Build Docker image
      - echo Build started on `date`
      - echo Building the Docker image...
      - sed -i "s/INGEST_PLACEHOLDER/$NRIA_LICENSE_KEY/g" Dockerfile
      - docker build -t python-flask .
      - docker tag python-flask:latest 490602924632.dkr.ecr.us-east-1.amazonaws.com/python-flask:latest

      # Update taskdef.json
      - echo "Loading envs to task definition"
      - sed -i "s/APP_PORT_PLACEHOLDER/$APP_PORT/g" taskdef.json
      - sed -i "s/APP_TOKEN_PLACEHOLDER/$APP_TOKEN/g" taskdef.json
      - sed -i "s/DB_HOST_PLACEHOLDER/$DB_HOST/g" taskdef.json
      - sed -i "s/DB_NAME_PLACEHOLDER/$DB_NAME/g" taskdef.json
      - sed -i "s/DB_PASSWORD_PLACEHOLDER/$DB_PASSWORD/g" taskdef.json
      - sed -i "s/DB_PORT_PLACEHOLDER/$DB_PORT/g" taskdef.json
      - sed -i "s/DB_USER_PLACEHOLDER/$DB_USER/g" taskdef.json
      - sed -i "s/NRIA_LICENSE_KEY_PLACEHOLDER/$NRIA_LICENSE_KEY/g" taskdef.json

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 490602924632.dkr.ecr.us-east-1.amazonaws.com/python-flask:latest
      - printf '[{"name":"release-3","imageUri":"490602924632.dkr.ecr.us-east-1.amazonaws.com/python-flask:latest"}]' > imagedefinitions.json
      - printf '{"ImageUri":"490602924632.dkr.ecr.us-east-1.amazonaws.com/python-flask:latest"}' > imageDetail.json

artifacts:
  files:
    - "**/*"
    - imagedefinitions.json
    - imageDetail.json
  secondary-artifacts:
    DefinitionArtifact:
      files:
        - appspec.json
        - taskdef.json
    ImageArtifact:
      files:
        - imageDetail.json
