# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main", "release_1", "release_2" ]
  pull_request:
    branches: [ "main", "release_1", "release_2" ]

permissions:
  contents: read

jobs:
  test-coverage:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install pipenv for users
      working-directory: ./
      run: pip install pipenv
    - name: Install dependencies for users
      working-directory: ./
      run: pipenv install --dev
    - name: Synchronize .lock file
      working-directory: ./
      run: pipenv sync
    - name: Run unit tests for users
      working-directory: ./
      run: pipenv run pytest --cov=src --cov-fail-under=60
